# The configurations of Docker to connect to this server app.
version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123098
      POSTGRES_DB: nest
    networks:
      - chatprogram
networks:
  chatprogram:
