-- AlterTable
ALTER TABLE "googleusers" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP;

-- AlterTable
ALTER TABLE "messages" ALTER COLUMN "sent" SET DATA TYPE TIMESTAMP;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP;
